version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: dipendentiv2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4749Gatto#!
      POSTGRES_DB: dipendenti
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
