package it.gls.dipendenti.shift.model;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZonedDateTime;

public record ShiftAssignment (
        Long id,
        Long employeeId,
        LocalDate date,
        LocalTime startTime,
        LocalTime endTime,
        boolean autoGenerated,
        ZonedDateTime modifiedAt,
        String note
) {}
