spring.application.name=.dipendenti
spring.datasource.url=jdbc:postgresql://localhost:5432/dipendenti
spring.datasource.username=admin
spring.datasource.password=4749Gatto#!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
